import { Navbar } from "@/components/Navbar";
import "./globals.css";
import s from "./app.module.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Miguel Ángel Bermúdez Cruz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="flex flex-col gap-8 min-h-screen bg-gray-300 justify-center dark:bg-black">
          <Navbar />
          <section className={s.content}>{children}</section>
          <Footer />
        </div>
      </body>
    </html>
  );
}
